### ISSUE TITLE
Automatic translation of C source

### ISSUE THREAD

**Issue by simonbyrne** [JuliaMath/Libm.jl#5]
One interesting idea from @tkelman in #3 is to automatically translate the C code from an existing libm. The openlibm/musl code is pretty clean (e.g. it doesn't make much use of pointers) so hopefully that should make it slightly less challenging.

It might be possible to make use of [Clang.jl](https://github.com/ihnorton/Clang.jl) for parsing the C code.

**Comment by ararslan** [comment]
We could also take inspiration from Mike Nolta's Fortran translation script that converted the Amos code to pure Julia in SpecialFunctions.jl.

**Comment by simonbyrne** [comment]
That is another option: fortunately C is much closer to Julia syntax, so should require fewer transformations to get something that is parseable.

**Comment by tkelman** [comment]
Though musl and freebsd (I'd use the upstream rather than our copy, unless there are things we've done to the code that we really want to keep) are much more alive and likely to continue changing over time than amos is.

**Comment by alyst** [comment]
It would be nice if the initial port is done automatically and at low cost. OTOH the main purpose of Libm.jl was to have native Julia implementation that Julian community can take care of. Which means automated updates might be complicated.

**Comment by tkelman** [comment]
"can take care of" in what way? This is likely to be enough code, and derived from enough other places, that keeping it updated with fixes and improvements made by its original authors and maintainers will be important. openlibm has been difficult to maintain and port fixes and new architectures to because it wasn't developed in a way that would make future updates/rebases simple.

**Comment by alyst** [comment]
Then the goal of `Libm.jl` is to make 3rd-party libm code accessible for Julia codegen/llvm optimizations in a hope that it would be faster than linking to that library?
I'm just concerned if any straightforward converter could generate the code that is on par with the original library. Otherwise the amount of custom tweaks would make the synchronization as complex as `openlibm` maintenance.

**Comment by tkelman** [comment]
I don't think anyone believes porting to Julia will magically make code faster than C. There might be some minor advantages of being able to runtime auto-vectorize based on the capabilities of the runtime system rather than the build-time system, and some possibilities for better inlining, but I think those are minor and likely more fragile than the overhead we'd pay by porting to Julia.

It would allow us to take known-good source code implementations that work well on the platform they're developed for, and make them available elsewhere using the Julia JIT instead of maintaining our own build system to build a libm in a standalone way.

**Comment by alyst** [comment]
But basically that would mean penalizing some Julia applications by ~50% due to non-optimal automatic conversion (well, we don't know the exact numbers yet, but it's quite risky to have limited control over code for central components like `libm`). IMHO that's a high price for excluding one library from the make file.

**Comment by ararslan** [comment]
We may want to look at Steven G. Johnson's Faddeeva stuff as a candidate for auto-translation. It's written in C++ and is the current source for Julia's error and Dawson functions as part of openspecfun.

Edit: Though I said in another thread that I think those should be in SpecialFunctions.jl rather than here.

**Comment by tkelman** [comment]
One (actually multiple) very out-of-date library that needs a lot of work, ref https://github.com/JuliaLang/openlibm/issues/101 and https://github.com/JuliaLang/openlibm/pull/118

**Comment by ViralBShah** [comment]
The obvious problem for source to source conversion is that you lose the benefits of being Julian. Maybe one can have Julian wrappers.

**Comment by ViralBShah** [comment]
The real issue is how will SIMD code in Julia be written. See the sleef code, and I was hoping perhaps better things are possible.

**Comment by ViralBShah** [comment]
Cc @eschnett

**Comment by tkelman** [comment]
Depends on exactly what you do to make it "more Julian," but should be possible to encode many of that kind of transformation too?

**Comment by simonbyrne** [comment]
I'm a bit less concerned about the maintenance than @tkelman: my experience with openlibm is that a lot of the maintenance was dealing with stuff like library headers and assembly instructions for rounding control modes, which we wouldn't need to worry about by having it in Julia. The code for math functions themselves actually changes fairly rarely.

The automatic conversion would be nice to have as a reference, but it's not necessary.

**Comment by eschnett** [comment]
One the main points of converting C code to Julia is to increase the level of abstraction. I expect that several functions are converted into one parameterized one that handles all of `Float32`, `Float64`, and `Float128` -- but there will be some exceptions. Function names will need to be simplified (no need to encode argument types). Calling conventions will be simplified, returning tuples instead of pre-declaring return variables and passing them by reference. For some operations, we will want to introduce new types, e.g. to represent high-precision floating point values by two `Float64` values with certain conventions. These new types should best follow the complete Julia convention for doing so. In some cases, we will also be able to use macros or generated functions to generated code at compile time, replacing current tedious manual stretches of code.

What we will want to keep is the current structure of the algorithms to e.g. calculate `sin` or `log`. The actual code will probably change so much that there's not much difference between copy-paste or just re-typing it.

I don't see much value in an automatic translation. It should be easier to just call the C functions via `ccall` in the short term.

**Comment by eschnett** [comment]
Regarding SIMD code: I expect the math functions to be parameterized, and by passing a SIMD vector to `sin`, it would automatically work. This requires a certain amount of care when implementing the functions -- e.g. no `if` statements, using `ifelse` instead -- but these modifications can be applied as the need arises.

**Comment by alyst** [comment]
While the automatic source conversion is being discussed, would it make sense to introduce some sort of code annotation that would help to track the original source in semi-automated way?

E.g.

``` julia
"""
    Normal Julia docstring
....

@sourceref <library_name> <version> <func_name> <source_file> <line_no>
"""
function erf(...)
...
end
```

**Comment by ViralBShah** [comment]
I think it may be too much effort to do so. Ideally we would do a whole bunch of functions first and figure out the right way to do this. If all goes well, perhaps there can be such annotations. 

The annotations have to then keep pace with upstream. If we have a well documented readable code base with good testing, I suspect this can be an independent codebase.

**Comment by eschnett** [comment]
@alyst I would keep a copy of the Sleef version used to write the Julia code in a git repository. When Sleef is updated and the new version is imported, Github will show a nice diff.

I don't think that there will be a one-to-one relation between Julia and C functions. Julia is more high level and has parameterized types, as well as operator overloading. I assume many Julia functions will correspond to several C functions.

Also -- much of Sleef's code is in helper functions that are never called from the outside. This is a self-consistent code base implementing e.g. much of `double-double` arithmetic. We might (or might not) want to restructure it. We definitively want to Juliaize it, i.e. introducing Julia types and respective operations, instead of passing pairs of references to doubles around.

**Comment by alyst** [comment]
There could be several source refs per function, of course. It's just to keep track of the (probably very loose) origins in a uniform way.

I'm just trying to digest what we've learned from PR #3. If Libm.jl is going to depart from the original code, then all comments and in-code documentation need to be transferred to .jl code.

**Comment by tkelman** [comment]
If the code we generate can avoid calls into the libjulia runtime and produces fairly standalone LLVM IR, I wonder if maybe we shouldn't contact `@hfinkel` and `@shibatch` and let them know this is happening, see if we can't get them onboard with the idea of using Julia as their code generator?

**Comment by eschnett** [comment]
We should contact `@hfinkel` anyway. I haven't communicated with `@shibatch` yet.

We will definitively need some runtime support from Julia: integers, floating-point numbers, tuples, `fastmath` support, inlining, generated functions, evaluating polynomials, operator overloading, type promotion. If we use generated functions, then we'll probably also need arrays. We probably don't need most of Base, but probably much of Core.

**Comment by oxinabox** [comment]
Let's close this.
Manual translation is now done.
(and a fair bit more than just translation)
