### ISSUE TITLE
Why Musl?

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaMath/Libm.jl#57]
https://github.com/JuliaMath/Libm.jl/tree/master/src/Musl

confusingly same as musl C library (I'm not sure if that has libm functionality).

Maybe Musl should be avoided, unless(?) there's a connection..

**Comment by musm** [comment]
see: https://github.com/JuliaMath/Libm.jl/issues/54

musl has libm functionality, this repo is currently undergoing a transformation (because it's a little confusing now with multiple competing submodules and such, and is thus confusing). The pure Sleef port which is what this repo is originally based on has now been moved to https://github.com/JuliaMath/Sleef.jl

This repo and whatever new name it has or not, will contain a curated and opinionated  package containing the best  implementations under the tradeoffs that we care for.

Thanks! Let me know if anything's not clear.
