### ISSUE TITLE
Please don't move repositories from orgs without consultation first

### ISSUE THREAD

**Issue by simonbyrne** [JuliaMath/Libm.jl#61]
I appreciate that you have recently been the dominant contributor, but this was originally intended as an open group repository, and the git history does contain contributions from several others including myself, and there is quite a bit of discussion in the issues that would be useful to keep.

**Comment by ViralBShah** [comment]
Was this originally in JuliaMath?

**Comment by ararslan** [comment]
Yes

**Comment by musm** [comment]
A little history:

Originally it did have codes from base, which simon worked on. And then this turned into a Sleef port, and so all of those function were removed soon after in favor of the Sleef code and the repo became Sleef.jl, which I solely worked on.

Since the following commit in October, the package basically started 'afresh' as I split it off into  Sleef.jl   and started anew with the package being renamed to Amal.jl
https://github.com/musm/Amal.jl/commit/19d111b58a334888a0345573678718d3308ddb99
With contributions from Chris updating the CI  badges. 

The issues I closed haven't been relevant for neither  `Amal` and `Sleef` as they both contain testing and benchmarking infrastructure.

I prefer to work on this and polish it and when the time is right I can  consider moving back to Julia Math, but I don't really see the point at this stage (package is not registered).

**Comment by simonbyrne** [comment]
I guess I should have spoken up when it was originally renamed, but I have been quite busy.

As far as a solution goes, can I suggest the following:

1. Move the repo back to JuliaMath.
2. You can create a fork of it under your own personal repository.
3. After you've created your fork, rename the main repository back to Libm.jl
4. If you would prefer, we can remove all the commits from 19d111b onwards.

In that way, the issues stay with the original repository.

**Comment by musm** [comment]
Sounds good except to remove from  https://github.com/musm/Libm.jl/commit/6dc6f942f614f30213d1486cb69552d702ff8398 onwards since that was when I began porting Sleef.jl

**Comment by musm** [comment]
Cool so https://github.com/musm/Amal.jl contains commits from  https://github.com/musm/Libm.jl/commit/19d111b58a334888a0345573678718d3308ddb99 onwards, which accurately reflects that I started from scratch 

I hope to work on that without much distraction.

**Comment by musm** [comment]
I won't be able to get to the rest till next, next weekend unfortunately (I'll try to finish if I have free time however)

**Comment by musm** [comment]
Nevermind it was easy enough to do.

**Comment by musm** [comment]
I'm trying to transfer but get the following permission error:
![image](https://cloud.githubusercontent.com/assets/4319522/22354629/1bba580c-e3f4-11e6-92ab-b1ace53b6ca3.png)

**Comment by ViralBShah** [comment]
Seems like it is back! Let me know if I can help in any way. I can't say how excited I have been about this effort.

**Comment by musm** [comment]
I'm still hitting the permission error when trying to transfer this to JuliaMath.

**Comment by ViralBShah** [comment]
I think that is perhaps because you may not have admin on JuliaMath. Let me check.

**Comment by ViralBShah** [comment]
I made you admin temporary so that you can transfer the repos. Hope that helps.

**Comment by simonbyrne** [comment]
thanks.
